### ISSUE TITLE
Making a tag favorite is looking very awkward

### ISSUE THREAD

**Issue by gurjyot** [Towhidn/CleanStrap#12]
The heart symbol to make a tag favorite is placed at a very awkward place where no one would easliy recognise that moreover the toop tip for heart symbol is not completely shown due to top menu. I would suggest to bring that heart symbol beneath the ask widget so that it can be easily seen and used.

![clean](https://cloud.githubusercontent.com/assets/6462850/5390598/2f0aacd8-8134-11e4-8881-1365ed2f9868.png)

**Comment by Towhidn** [comment]
it doesn't look much better in left. do you have any suggestions about the positions?
also tooltip is created using bootstrap which doesn't have this issue(checked in firefox and chrome). which browser are you using?
