### ISSUE TITLE
Comment on a question is having some issues

### ISSUE THREAD

**Issue by gurjyot** [Towhidn/CleanStrap#13]
After doing a comment on a question, if I immediately try to comment again on the same quesiton the the page reloads and shows on button to either comment or answer. Have a look in the pic below.

![cle](https://cloud.githubusercontent.com/assets/6462850/5390657/2b4a4b7a-8135-11e4-86da-0732935f0f55.png)

**Comment by Towhidn** [comment]
it's not an issue, it's normal Q2A behavior. 
thirst time answer or comment is submitted, it will be posted using ajax and without page load, but next time Q2A will act as if JS is disabled and reload page to sent new request.
