### ISSUE TITLE
Login button shift towards right which shouldn't be happening

### ISSUE THREAD

**Issue by gurjyot** [Towhidn/CleanStrap#15]
When I click Login button then it shifts a little bit towards right which in my case is creating a problem because it is going a little out of screen. Secondly when the login form drops from top then the cross to cancle is placed at the border line of top menu which is making it way difficult to watch. Have a look.

![cross](https://cloud.githubusercontent.com/assets/6462850/5390785/abeced76-8137-11e4-9873-e9527a83c81f.png)

Moreover in mobile view, when we click on login button then the cross for login form is coming just over the login button which is even very difficult to be seen with black login button.

**Comment by Towhidn** [comment]
issue is solved. thanks for reporting.

**Comment by gurjyot** [comment]
Yes it is solved... :)
