### ISSUE TITLE
The search button and login button are not aligned properly

### ISSUE THREAD

**Issue by gurjyot** [Towhidn/CleanStrap#17]
Very small alignment issue is there for search bar and login button for both desktop and mobile view. Search button is little down as compared to login button. Its not a big issue but by fixing this, this theme can take one more step toward perfect.

**Comment by Towhidn** [comment]
although I didn't notice any problems in normal sized screens in 3
browsers. just removed extra border.

**Comment by gurjyot** [comment]
Thanks man, it surely is looking better to me now... :)
