### ISSUE TITLE
Couldn't find the option to show usercard

### ISSUE THREAD

**Issue by gurjyot** [Towhidn/CleanStrap#19]
I have seen this theme when first released and I know that usercard was added to this theme which made it one of the top themes so far. But I couldn't find a way to show usercard on my site. How to activate that and if that is not added to this version yet then please add that. Usercard is a great addition and can make huge difference.

**Comment by Towhidn** [comment]
It's activated by default. can you send me your website's URL to check this issue?

**Comment by gurjyot** [comment]
Yes now its working... Don't know why it was not showing on the first installation.
