### ISSUE TITLE
User gravatar is showing when selected not to show any avatar

### ISSUE THREAD

**Issue by gurjyot** [Towhidn/CleanStrap#20]
I think there is some issue, I have set not to show any avatar from my profile but still my gravatar is showing. Please have a look at this issue.

**Comment by Towhidn** [comment]
in "Admin > users" set "Avatar size on questions" to 0 to stop showing questions in list.
you should also be able to uncheck "Allow Gravatar avatars" to stop showing avatars.

**Comment by gurjyot** [comment]
I have tried that but the Gravatars are still showing. I have opened a new issue for this with some more specific details so I am closing this issue with a link to that issue. #27
