### ISSUE TITLE
User avatar is showing twice in front of question

### ISSUE THREAD

**Issue by gurjyot** [Towhidn/CleanStrap#22]
When a common pic if selected by site to show as user avatar for all users, then that pic is showing twice in front of question on home page. Have a look at the image.

![user](https://cloud.githubusercontent.com/assets/6462850/5418510/cbab5dd2-8268-11e4-8506-9779ed57c16f.png)

**Comment by Towhidn** [comment]
it's fixed in new version.

**Comment by gurjyot** [comment]
Thanks for the fix... :)
