### ISSUE TITLE
Cleanstrap and Q&A 1.7 + Bootstrap 3.3.1

### ISSUE THREAD

**Issue by JoZ3** [Towhidn/CleanStrap#24]
any chance to update the theme for work with the last Q&A 1.7 and the latest Bootstrap version, currently there are incompatibilities between the theme and the new versions.

**Comment by Towhidn** [comment]
It seems that only known issue with Q2A 1.7 compatibility was Responsive Navigation Button which is fixed. please let me know if there are any issues.
bootstrap is updated too.
