### ISSUE TITLE
Replaces the default banner

### ISSUE THREAD

**Issue by fulldecent** [Towhidn/CleanStrap#34]
If the user has set their own banner and then load CleanStrap then that banner is replaced by CleanStrap's logo

![screen shot 2015-03-11 at 3 15 03 pm](https://cloud.githubusercontent.com/assets/382183/6604807/91cffde6-c801-11e4-8810-0926b92a10eb.png)

**Comment by Towhidn** [comment]
Visit "Theme Options" & upload old logo. you can make the replacement from "Admin > layouts" too.
also there is another logo option in theme options to allow adding an smaller logo for devices with smaller screens(mobile phones).
