### ISSUE TITLE
The login form is not showing after I updated cleanstrap on q2a 1.6.3

### ISSUE THREAD

**Issue by gurjyot** [Towhidn/CleanStrap#35]
As I updated the theme on my website the login form is not showing. The form which I am talking about is the one which comes after we click the black button on top right corner.
When I click that then a white screen appears.

**Comment by Towhidn** [comment]
I don't get this issue on development environment or 2 other sites I keep updating with latest version.

can you send me the address to your site?

**Comment by gurjyot** [comment]
I have mailed you my site link, I don't want my site to be public.

**Comment by Towhidn** [comment]
issue happened when Fixed Navigation option was enable to make header stick to top. now it's solved.

**Comment by gurjyot** [comment]
Now the login form is showing, but the "login" text on login button is missing and secondly, when I click the button then it is redirecting me to homepage without loging me in. So I am not able to login using this form.

**Comment by gurjyot** [comment]
Thanks for the update, now everything looks good but it's not logging me in even now. When I hit the login button then the page just refreshes and nothing happens.
