### ISSUE TITLE
Logo, mobile logo and ask button for mobile view are overlapping

### ISSUE THREAD

**Issue by gurjyot** [Towhidn/CleanStrap#36]
Before the update everything was good but now logo, mobile logo and ask button (question mark icon for mobile view) are overlapping. This is happening in mobile view, please fix this.

**Comment by Towhidn** [comment]
you can download the version before this changes here:
https://github.com/Towhidn/CleanStrap/tree/a652d6f7670f8664460103bd0c211f3c7adc0c52

also I didn't make any major changes in this section. if you send me the link to your site I'll be able to check it.

**Comment by Towhidn** [comment]
Issue happened because of Bootstrap update. it's fixed

**Comment by gurjyot** [comment]
This fixed some of the problem but now the mobile size logo is not showing.

**Comment by Towhidn** [comment]
visit theme options and upload small sized logo again. it should fix the problems.

**Comment by gurjyot** [comment]
I can't change the logo as I can't login to my website because of this issue. #35

**Comment by Towhidn** [comment]
please upload it again and tell me how it's going.

**Comment by gurjyot** [comment]
Yes the logo is showing now, but please fix the login problem. Because of that none of my website users are able to login.

**Comment by Towhidn** [comment]
I think your theme is not updated, it issue was fixed with 935947262bdb4c584e410c6f46e0efb5bb17215a. I updated the [demo](http://demo.qa-themes.com/cleanstrap/ "CleanStrap Demo") and it works. also, in demo you can see that I set new user widget to only show users who uploaded their avatars.

**Comment by gurjyot** [comment]
But in your demo only, when I open my profile then my gravatar is showing,
but I haven't selected my gravatar to show. How come this is happening??

**Comment by Towhidn** [comment]
if you want you can send me your site's administrator login info and I'll check it out.

**Comment by gurjyot** [comment]
Sorry for the late reply. You are right, your updates fixed the issue.
