### ISSUE TITLE
Not able to save widget settings

### ISSUE THREAD

**Issue by Smilefounder** [Towhidn/CleanStrap#42]
The issue is after you modify the widget setting in themes widget page. We can not save the setting after update somethings.

**Comment by Towhidn** [comment]
This is most likely a php version issue. if you are using old versions of php which doesn't support JSON this feature won't work.

**Comment by mavencode01** [comment]
@Towhidn I'm having the same issues, and I'm pretty sure it was working before.

**Comment by mavencode01** [comment]
@Smilefounder were you able to fix this ?

**Comment by mavencode01** [comment]
@Towhidn you are absolutely correct - thanks!

Works now
