### ISSUE TITLE
there are blanks in the main page  between  question and  widgets sidebars,why?

### ISSUE THREAD

**Issue by aohan237** [Towhidn/CleanStrap#44]
in  the  main page ,shows  like  this ,there are  large blanks between the  questions and widgets 
the  screenshot:
![default](https://cloud.githubusercontent.com/assets/3992281/9459053/2d724dbc-4b29-11e5-8570-728c470eaa69.jpg)

but  in  any other pages,like activity,question  etc,  it  acts normal
the  screenshot:
![2](https://cloud.githubusercontent.com/assets/3992281/9459069/65157f96-4b29-11e5-9b61-5d10b8942142.png)

this  really bothers me a  lot ,i dont  know why.
I'm very  appericate if  you  can solve me  the problem.

Thanks  a  lot

**Comment by Towhidn** [comment]
If you send me the link to your website I'd be able to check it out. there are also other homepage layouts available in "Theme Options > Layouts" under "Home Page" section which might solve this problem.

**Comment by aohan237** [comment]
here is  my  website :    www.tumujie.com
and  i  have  tried to  config the "Theme Options > Layouts" under "Home Page" section,but  failed  to fix it.
Thanks  again

**Comment by Towhidn** [comment]
enable "Toggle question list in home" option in "Theme Options > layout". also the list you are seeing is probably a widget in "Home 2"  section, remove it from "Theme Widgets" page.

**Comment by aohan237** [comment]
i  have   enabled  "Toggle question list in home" option in "Theme Options > layout"   but  nothing chaged

in  "Theme Widgets" page. i can  only  add or remove widgets   but  cant  remove  like "home 2"  sections.   there is  no operation to  remove it  except  from  the  source  code...

here  is  the  screenshot:

![qq](https://cloud.githubusercontent.com/assets/3992281/9465761/ed239f0c-4b61-11e5-81c7-d6047df2c11f.jpg)

**Comment by Towhidn** [comment]
It's possible that your hosting provider uses an old version of php which doesn't support json. it's one of the known reasons of problems in configuring widgets and can be solved by upgrading php to latest version.

**Comment by aohan237** [comment]
no,my  host  is linode vps uses  ubuntu 14.04  ,and  i  just  upgrade  it
a week ago,so  the php will be updated.

so  It  might not be  the host's  problem

无所谓好或不好，人生一场虚空大梦，韶华白首，不过转瞬。惟有天道恒在，往复循环，不曾更改

2015-08-25 21:43 GMT+08:00 Towhid <notifications@github.com>:
