### ISSUE TITLE
By any chance are you planning to release the same theme for WordPress

### ISSUE THREAD

**Issue by qamate** [Towhidn/CleanStrap#50]
We do have a community of Software Testing Professionals where we have a Question2Answer site. We use CleanStrap theme. It looks pleasing.

https://softwaretestingboard.com/qna/

We are looking for very similar theme for WordPress.

https://softwaretestingboard.com/

That's where we have hosted our main site.

Are you planning to release very similar theme for WordPress as well?

Let me know.

-Mayur

**Comment by TohidN** [comment]
Thanks for using CS. At the moment creating a new theme is not in my schedule. but I might publish one new responsive theme and one mobile theme with same styling by the end of November. it all depends on how much free time I will have.

**Comment by qamate** [comment]
@Towhidn I understand. Thank you for the update.

**Comment by qamate** [comment]
@Towhidn is there any way to contact you apart from GitHub?

-Mayur

**Comment by TohidN** [comment]
here: http://qa-themes.com/contact-us
